### ISSUE TITLE
Update regex crate for regex_dna

### ISSUE THREAD

**Issue by llogiq** [TeXitoi/benchmarksgame-rs#12] opened 2015-09-21 14:52 UTC
I think this will also require regex_syntax, which will need some Makefile hackery to get running.

**Comment by BurntSushi** [comment] 2015-09-21 15:17
I think this is a dupe of https://github.com/TeXitoi/benchmarksgame-rs/issues/3, or at the very least, would be resolved by it.

**Comment by llogiq** [comment] 2015-09-21 15:24
Agreed. I should have read your issue first.

**Closed as completed** 2015-09-21 15:24 UTC
